# Generated by Django 4.0.1 on 2022-04-29 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.location')),
            ],
        ),
    ]
