# Generated by Django 4.0.1 on 2022-04-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='name',
            new_name='department_name',
        ),
    ]
