# Generated by Django 4.0.1 on 2022-04-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(default='null'),
        ),
    ]
