# Generated by Django 4.0.1 on 2022-04-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_registration_state_registration_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='phone',
            new_name='mobile_number',
        ),
    ]
