# Generated by Django 4.0.1 on 2022-04-30 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_rename_name_departments_department_name'),
        ('public', '0004_rename_mobile_number_registration_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaints_subject', models.CharField(default='null', max_length=255)),
                ('complaints_text', models.TextField(default='null')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('public_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.registration')),
                ('selected_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.departments')),
            ],
        ),
    ]
