# Generated by Django 4.0.1 on 2022-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_messages_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('department_user', 'Department User'), ('user', 'User')], default='user', max_length=15),
        ),
    ]
