# Generated by Django 4.0.1 on 2022-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_alter_messages_department_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=15),
        ),
    ]
