# Generated by Django 4.0.1 on 2022-04-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_alter_complaints_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='reply',
            field=models.TextField(default='null'),
        ),
    ]
