# Generated by Django 4.0.1 on 2022-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_complaints_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='reply',
            field=models.TextField(default='null', null=True),
        ),
    ]
