# Generated by Django 4.0.1 on 2022-04-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0003_rename_name_departments_department_name'),
        ('department', '0005_alter_registration_working_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='working_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.departments'),
        ),
    ]
